### ISSUE TITLE
how does one add more xpra parameters to the android client?

### ISSUE THREAD

**Issue by zenny** [dscho/Xpra#1]
Hi,

Can you elaborate on how to add new parameters like:

```
--desktop-scaling=value
--sharing=yes|no
--readonly=yes|no

```

to the xpra android client? Thanks and happy holidays!

**Comment by dscho** [comment]
Sorry, I missed this. I do not work with xpra anymore, as it broke my usage on Ubuntu (more often than not, it showed just a white window), so this fork fell unmaintained. I will archive it.
